name: iti
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python
  - wandb
  - ipywidgets
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=11.8
  - lightning
  - scikit-learn
  - scikit-image
  - tqdm
  - numpy
  - sunpy
  - aiapy
  - drms
  - astropy
  - pandas
  - wandb
  - matplotlib
  - pip

